apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
{{- include "mychart_labels" . | indent 2 }}
data:
  myvalue: "Hello World"
  {{- $relname := .Release.Name -}}
  {{- range $key, $val := .Values.favorite }}
  {{ $key }}: {{$val | quote }}
  {{- if eq $val "coffee" }}
  mug: true
  {{- end }}
  {{- end}}
  release: {{ $relname }}
  toppings: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    {{ $index }}: {{ $topping }}
    {{- end }}
{{ include "mychart_app" . | indent 4}}